config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :functionaries do
    resources :proclamations
  end

  get 'functionary/:id/gains_json' => 'functionaries#gains_json', as: :gains_json, :defaults => { :format => 'json' }
  get 'functionary/:id/gains_per_year_json' => 'functionaries#gains_per_year_json', as: :gains_per_year_json, :defaults => { :format => 'json' }
  get 'functionary/:id/total_gains_json' => 'functionaries#total_gains_json', as: :total_gains_json, :defaults => { :format => 'json' }

end

app/models/functionary.rb
class Functionary < ActiveRecord::Base

  has_many :proclamations
  has_many :internal_numbers
  has_many :gains, through: :proclamations
  has_many :reimbursements, through: :proclamations
  has_many :estates, through: :proclamations
  has_many :chattels, through: :proclamations
  has_many :jobs, through: :proclamations

  # FILTERRIFIC
  # define ActiveRecord scopes for
  # :search_query, :sorted_by, :with_country_id, and :with_created_at_gte
  filterrific(
      default_filter_params: { sorted_by: 'full_name_asc' },
      available_filters: [
          :sorted_by,
          :search_query
          #:with_created_at_gte
      ]
  )

  #self.per_page = 20
  paginates_per 50

  scope :search_query, lambda { |query|
                       # Searches the users table on the 'first_name' and 'last_name' columns.
                       # Matches using LIKE, automatically appends '%' to each term.
                       # LIKE is case INsensitive with MySQL, however it is case
                       # sensitive with PostGreSQL. To make it work in both worlds,
                       # we downcase everything.
                       return nil  if query.blank?

                       # condition query, parse into individual keywords
                       terms = query.to_s.downcase.split(/\s+/)

                       # replace "*" with "%" for wildcard searches,
                       # append '%', remove duplicate '%'s
                       terms = terms.map { |e|
                         (e.gsub('*', '%') + '%').gsub(/%+/, '%')
                       }
                       # configure number of OR conditions for provision
                       # of interpolation arguments. Adjust this if you
                       # change the number of OR conditions.

                       #POSTGRESQL DEPENDENCY: UNACCENT EXTENSION!!! (create extension unaccent;)
                       num_or_conds = 3
                       where(
                           terms.map {
                             or_clauses = [
                                 "LOWER(UNACCENT(functionaries.first_name)) LIKE ?",
                                 "LOWER(UNACCENT(functionaries.last_name)) LIKE ?",
                                 "LOWER(UNACCENT(functionaries.full_name)) LIKE ?"
                             ].join(' OR ')
                             "(#{ or_clauses })"
                           }.join(' AND '),
                           *terms.map { |e| [e] * num_or_conds }.flatten
                       )
                     }

  scope :sorted_by, lambda { |sort_option|
                    # extract the sort direction from the param value.
                    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
                    case sort_option.to_s
                      when /^full_name_/
                        # Simple sort on the name colums
                        order("LOWER(functionaries.full_name) #{ direction }")
                      else
                        raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
                    end
                  }

  scope :with_created_at_gte, lambda { |ref_date|
                              where('functionaries.created_at >= ?', ref_date)
                            }

  STRUCTURE = ['Interné číslo', 'ID oznámenia', 'meno', 'oznámenie za rok',
               'oznámenie bolo podané', 'vykonávané funkcie', 'príjmy za rok',
               'paušálne náhrady za rok", "ostatné príjmy za rok',
               'spĺňa podmienky nezlučiteľnosti výkonu funkcie verejného funkcionára s výkonom iných funkcií, zamestnaní alebo činností podľa čl. 5 ods. 1 a 2 u. z. 357/2004',
               'vykonáva nasledovné zamestnanie v pracovnom pomere alebo obdobnom pracovnom vzťahu alebo štátnozamestnaneckom vzťahu (čl. 7 ods. 1 písm. b) u. z. 357/2004)',
               'vykonáva nasledovnú podnikateľskú činnosť (čl. 5 ods. 2 až 5 a čl. 7 ods. 1 písm. b) u. z. 357/2004)',
               'počas výkonu verejnej funkcie má tieto funkcie (čl. 7 ods. 1 písm. c) u. z. 357/2004)',
               'nehnuteľný majetok',
               'hnuteľný majetok, majetkové právo alebo iná majetková hodnota, existujúce záväzky, ktorých menovitá hodnota, bežná cena alebo peňažné plnenie presahuje 35-násobok minimálnej mzdy']

  def self.options_for_sorted_by
    [
        ['Name (a-z)', 'full_name_asc'],
        ['Name (z-a)', 'full_name_desc']
    ]
  end

  def self.get_all_functionaries
    require 'rubygems'
    require 'nokogiri'
    require 'open-uri'

    begin
      page = Nokogiri::HTML(open("http://www.nrsr.sk/web/Default.aspx?sid=vnf/zoznam&ViewType=1"))
    rescue OpenURI::HTTPError
      puts "404"
    end

    div_form_text = page.at_xpath('//div[@class="form"]').text

    div_form = page.css('div.form a').map { |link| link['href']}
    div_form.select { |link| !link.nil? && link.include?("Default") }

    div_form.each do |n|
      if n.nil?
        puts "nil"
      else
        parse_url("http://www.nrsr.sk/web/" + n)
      end
    end
  end

  def self.parse_url(url)
    require 'rubygems'
    require 'nokogiri'
    require 'open-uri'

    url = URI.escape(url)
    if (url.nil?)
      puts "nil"
    else
      begin
        page = Nokogiri::HTML(open(url))
      rescue OpenURI::HTTPError
        puts "404"
      else
        last_column = ""
        html_text_array = []
        if !page.nil? && !page.css("#_sectionLayoutContainer_ctl01_OutPut").nil? && !page.css("#_sectionLayoutContainer_ctl01_OutPut").css("table")[0].nil?
          page.css("#_sectionLayoutContainer_ctl01_OutPut").css("table")[0].css("tr").each do |tr|
            text = tr.css("td").text
            html_text_array << text
          end
          parse_html_text_rows(html_text_array)
        end
      end
    end
  end

  def self.parse_html_text_rows(html_text)
    functionary = nil
    internal_number = nil
    proclation = nil
    job = nil
    gain = nil

    index = 0
    text = html_text
    while index < text.length do
      f = text[index]
      if f.include?("Interné číslo") then
        internal_number = InternalNumber.where(value: text[index+1]).first_or_create
        index = index + 1
      elsif f.include?("ID oznámenia") then
        proclamation = Proclamation.where(global_id: text[index+1]).first_or_create
        index = index + 1
      elsif f.include?("meno:") then
        name = text[index+1].split(" ").select { |n| !n.include? '.'}
        functionary = Functionary.where(first_name: name[1], last_name: name[2], full_name: text[index+1]).first_or_create
        proclamation.update_attributes(functionary_id: functionary.id)
        index = index + 1
      elsif f.include?("rodné priezvisko") then
        if functionary
          functionary.update_attributes(surname_at_birth: text[index+1])
        end
        index = index + 1
      elsif f.include?("oznámenie za rok") then
        if proclamation
          proclamation.update_attributes(year: text[index+1])
        end
        index = index + 1
      elsif f.include?("oznámenie bolo podané") then
        if proclamation
          proclamation.update_attributes(adhibited_at: text[index+1])
        end
        index = index + 1
      elsif f.include?("vykonávané funkcie") then
        if proclamation
          proclamation.update_attributes(administrative_functions: text[index+1])
        end
        index = index + 1
      elsif f.include?("príjmy za rok") then
        gains = text[index+1].split('(')
        puts "GAINS: #{gains}"
        gains.each_with_index {|g, i|
          if i == 0
            if gains.size >= 2
              gain = Gain.where(category: 0, value: gains[0], currency: gains[1], proclamation_id: proclamation.id).first_or_create
              if gain
                gain.update_attributes(category: 0, value: gains[0], currency: gains[1], proclamation_id: proclamation.id)
              end
            end
          elsif i == 1
            g = g.split(')')
            if g[1] && !g[1].split(' ').nil? && g[1].split(' ').size >= 2
              gain = Gain.where(category: 1, value: g[1].split(' ')[0], currency: g[1].split(' ')[1], proclamation_id: proclamation.id).first_or_create
            end
          end
        }
        index = index + 1
      elsif f.include?("paušálne náhrady za rok") then
        reinbursements = text[index+1].split(' ')
        reinbursements.each_with_index {|g, i|
          if g.include?("z výkonu verejnej funkcie")
            reinbursement = Reimbursement.where(category: 0, value: gains[i-2], currency: gains[i-1], proclamation_id: proclamation.id).first_or_create
          elsif g.include?("iné")
            reimbursement = Reimbursement.where(category: 1, value: gains[i-2], currency: gains[i-1], proclamation_id: proclamation.id).first_or_create
          end
        }
        index = index + 1
      elsif f.include? "ostatné príjmy za rok" then
        puts f #gain = Gain.first_or_create(category: 2, value: gains[i-2], currency: gain[i-1], functionary_id: functionary.id, proclamation_id: proclamation.id)
      elsif f.include? "spĺňa podmienky nezlučiteľnosti výkonu funkcie verejného funkcionára s výkonom iných funkcií, zamestnaní alebo činností" then
        if text[index+1].include? "áno" then
          proclamation.update_attributes(satisfies_weird_conditions: true)
        elsif text[index+1].include? "nie" then
          proclamation.update_attributes(satisfies_weird_conditions: false)
        end
        index = index + 1
      elsif f.include? "vykonáva nasledovné zamestnanie v pracovnom pomere alebo obdobnom pracovnom vzťahu alebo štátnozamestnaneckom vzťahu" then
        if proclamation
          job = Job.where(proclamation_id: proclamation.id, description: text[index+1]).first_or_create
        end
        index = index + 1
      elsif f.include? "Dlhodobo plne uvoľnený na výkon verejnej funkcie podľa Zákonníka práce" then
        if f.split(':').include? "nie" then

app/controllers/functionaries_controller.rb
class FunctionariesController < ApplicationController

  def index
    @filterrific = initialize_filterrific(
        Functionary,
        params[:filterrific],
        select_options: {
            sorted_by: Functionary.options_for_sorted_by
        }
    ) or return
    @functionaries = @filterrific.find.page(params[:users_page]).per(10)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @functionary = Functionary.find(params[:id])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def gains_json
    json = { "gains" => []}
    @functionary = Functionary.find(params[:id])
    @functionary.gains.includes(:proclamation).each do |gain|
      value = gain.convert_value_to_eur
      json["gains"].push({"value" => value, "year" => gain.proclamation.year})
    end

    respond_to do |format|
      format.json { render :json => json }
    end
  end

  def gains__per_year_json
    json = { "gains" => []}
    @functionary = Functionary.find(params[:id])
    total = 0
    @functionary.gains.includes(:proclamation).each do |gain|
      value = gain.convert_value_to_eur
      total += value
    end
    json["gains"].push({"total_value" => total})

    respond_to do |format|
      format.json { render :json => json }
    end
  end

  def total_gains_json
    json = { "gains" => []}
    @functionary = Functionary.find(params[:id])
    total = 0
    @functionary.gains.includes(:proclamation).each do |gain|
      value = gain.convert_value_to_eur
      total += value
    end
    json["gains"].push({"total_value" => total})

    respond_to do |format|
      format.json { render :json => json }
    end
  end

  private

end

app/helpers/functionaries_helper.rb
module FunctionariesHelper
end

app/views/functionaries/_list.html.erb
<div id="filterrific_results">

  <table id="functionaries_table" class="table table-bordered">
    <thead class="tableheader">
    <tr>
      <th class="hidden-xs">Name</th>
      <th class="hidden-xs">Surname at birth</th>
    </tr>
    </thead>
    <tbody>
    <% functionaries.each do |functionary| %>
        <tr class="row-one">
          <td class="hidden-xs"><%= link_to(functionary.full_name, functionary_path(functionary)) %></td>
          <td class="hidden-xs"><%= functionary.surname_at_birth %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <div style="text-align: center;">
    <%= paginate @functionaries, param_name: :functionary_page, theme: 'bootstrap' %>
  </div>

</div>

app/views/functionaries/_proclamation.html.erb
<section id="content">

  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="" data-parent="#accordion" href="#<%= proclamation.id %>-collapseOne">Vykonávané
          funkcie</a> <!--collapse-->
      </h4>
    </div>
    <div id="<%= proclamation.id %>-collapseOne" class="panel-collapse "> <!--collapse-->
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <table class="table table-hover">
              <thead>
              <tr>
                <th>Popis</th>
              </tr>
              </thead>
              <tbody>
              <% proclamation.jobs.each do |job| %>
                  <tr>
                    <td><%= job.description %></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="" data-parent="#accordion" href="#<%= proclamation.id %>-collapseOne">Príjmy</a> <!--collapse-->
      </h4>
    </div>
    <div id="<%= proclamation.id %>-collapseOne" class="panel-collapse "> <!--collapse-->
      <div class="panel-body">
        <div class="row">
          <div class="col-md-4">
            <table class="table table-hover">
              <caption>Príjmy z výkonu verejnej funkcie</caption>
              <thead>
              <tr>
                <th>Suma</th>
              </tr>
              </thead>
              <tbody>
              <% proclamation.gains.select { |g| g.category == 'administrative' }.each do |gain| %>
                  <tr>
                    <td><%= gain.value > 0 ? gain.convert_value_to_eur.to_s+" €" : '-' %></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>

          <div class="col-md-4">
            <table class="table table-hover">
              <caption>Iné príjmy</caption>
              <thead>
              <tr>
                <th>Suma</th>
              </tr>
              </thead>
              <tbody>
              <% proclamation.gains.select { |g| g.category == 'other' }.each do |gain| %>
                  <tr>
                    <td><%= gain.value > 0 ? gain.convert_value_to_eur.to_s+" €" : '-' %></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>

          <div class="col-md-4">
            <table class="table table-hover">
              <caption>Ostatné príjmy</caption>
              <thead>
              <tr>
                <th>Suma</th>
              </tr>
              </thead>
              <tbody>
              <% proclamation.gains.select { |g| g.category == 'administrative' }.each do |gain| %>
                  <tr>
                    <td><%= gain.value > 0 ? gain.convert_value_to_eur.to_s+" €" : '-' %></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="" data-parent="#accordion" href="#<%= proclamation.id %>-collapseTwo">Náhrady</a> <!--collapse-->
      </h4>
    </div>
    <div id="<%= proclamation.id %>-collapseTwo" class="panel-collapse "> <!--collapse-->
      <div class="panel-body">
        <div class="row">
          <div class="col-md-4">
            <table class="table table-hover">
              <caption>Paušálne náhrady</caption>
              <thead>
              <tr>
                <th>Suma</th>
              </tr>
              </thead>
              <tbody>
              <% proclamation.reimbursements.select { |r| r.category == 'administrative' }.each do |reimbursement| %>
                  <tr>
                    <td><%= reimbursement.value > 0 ? reimbursement.value.to_s+" €" : '-' if reimbursement.value %></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>

          <div class="col-md-4">
            <table class="table table-hover">
              <caption>Iné náhrady</caption>
              <thead>
              <tr>
                <th>Suma</th>
              </tr>
              </thead>
              <tbody>
              <% proclamation.reimbursements.select { |r| r.category == 'other' }.each do |reimbursement| %>
                  <tr>
                    <td><%= reimbursement.value > 0 ? reimbursement.value.to_s+" €" : '-' if reimbursement.value %></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="" data-parent="#accordion" href="#<%= proclamation.id %>-collapseThree">Majetok</a> <!--collapse-->
      </h4>
    </div>
    <div id="<%= proclamation.id %>-collapseThree" class="panel-collapse "> <!--collapse-->
      <div class="panel-body">
        <div class="row">

          <div class="col-md-4">
            <table class="table table-hover">
              <caption>Hnuteľný majetok</caption>
              <thead>
              <tr>
                <th>Suma</th>
              </tr>
              </thead>
              <tbody>
              <% proclamation.gains.select { |g| g.category == 'administrative' }.each do |gain| %>
                  <tr>
                    <td><%= gain.value > 0 ? gain.convert_value_to_eur.to_s+" €" : '-' %></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
          <div class="col-md-4">
            <table class="table table-hover">
              <caption>Nehnuteľný majetok</caption>
              <thead>
              <tr>
                <th>Suma</th>
              </tr>
              </thead>
              <tbody>
              <% proclamation.gains.select { |g| g.category == 'administrative' }.each do |gain| %>
                  <tr>
                    <td><%= gain.value > 0 ? gain.convert_value_to_eur.to_s+" €" : '-' %></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>


</section>

app/views/functionaries/index.html.erb
<h1 style="color:white;">Functionaries</h1>
<%#
  Filterrific adds the `form_for_filterrific` view helper:
  * adds dom id 'filterrific_filter'
  * applies javascript behaviors:
      * AJAX form submission on change
      * AJAX spinner while AJAX request is being processed
  * sets form_for options like :url, :method and input name prefix
%>
<%= form_for_filterrific @filterrific do |f| %>
    <div class="well">
      <div class="row">
        <div class="col-md-3">
          Search
          <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
          <%= f.text_field(
                      :search_query,
                      class: 'filterrific-periodically-observed'
              ) %>
        </div>

        <div class="col-md-3">
          Sorted by
          <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by]) %>
        </div>
        <div class="col-md-3">
          <%= link_to(
                      'Reset filters',
                      reset_filterrific_url,
              ) %>
        </div>
        <%# add an automated spinner to your form when the list is refreshed %>
        <%= render_filterrific_spinner %>
      </div>
    </div>
<% end %>

<%= render(
            partial: 'functionaries/list',
            locals: {functionaries: @functionaries}
    ) %>

<script>
    $('#filterrific_with_created_at_gte').datepicker({
        format: 'yyyy-mm-dd',
        autoclose: true
    });
    $('#filterrific_with_created_at_gte').on('changeDate', function (ev) {
        $(this).datepicker('hide');
    });
</script>

app/views/functionaries/index.js.erb
<% js = escape_javascript(
  render(partial: 'functionaries/list', locals: { functionaries: @functionaries })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/functionaries/show.html.erb
<h2><%= @functionary.full_name %></h2>


<div id="graphs">

</div>

<ul class="nav nav-tabs">
  <% @functionary.proclamations.each_with_index do |proclam, i| %>
      <li class="<%= i ==0 ? "active" : "" %>">
        <a data-toggle="tab" href="#proclamation-<%= proclam.year %>"><%= proclam.year %></a>
      </li>

  <% end %>
</ul>

<div class="tab-content">

  <% @functionary.proclamations.each_with_index do |proclam, i| %>
      <div id="proclamation-<%=proclam.year%>" class="tab-pane fade <%= i==0 ? "in active" : ""%>">
        <%= render 'proclamation', proclamation: proclam %>
      </div>
    <%end%>
</div>


<script>
    barchart("<%= @functionary.id.to_s %>");
</script>