config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :functionaries do
    resources :proclamations
  end

  get 'functionary/:id/gains_json' => 'functionaries#gains_json', as: :gains_json, :defaults => { :format => 'json' }
  get 'functionary/:id/gains_per_year_json' => 'functionaries#gains_per_year_json', as: :gains_per_year_json, :defaults => { :format => 'json' }
  get 'functionary/:id/total_gains_json' => 'functionaries#total_gains_json', as: :total_gains_json, :defaults => { :format => 'json' }

end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to 'Datack', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <div class="pull-right">
          <ul class="nav navbar-nav">
            <%= render 'layouts/navigation_links' %>
          </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'Functionaries', functionaries_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DatahackHackathon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- CSS -->
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
  <link href="css/style.css" rel="stylesheet">

  <!-- JS -->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <script src="http://d3js.org/d3.v3.min.js"></script>

</head>
<body>
<header>
  <%= render 'layouts/navigation' %>
</header>
    <main role="main">
      <div class="container" style="padding-top:50px;">
        <%= yield %>
      </div>
    </main>
</body>
</html>